### ISSUE TITLE
AuthenticateWithEmail not working

### ISSUE THREAD

**Issue by OldWartHog** [NicklasWallgren/ewelink#6]
I tried the initiate power request example but my login failed with this error:

failed to authenticate unable to authenticate using email. ewelink.apiError{Code:403, Message:"Sign:oauthClient enable invalid", Cause:""}

**Comment by NicklasWallgren** [comment]
They recently invalidate the app id and app secret.

Try the latest version.

**Comment by OldWartHog** [comment]
Thanks, that worked.  

Martin

**Comment by NicklasWallgren** [comment]
Great!, closing the issue.
